[package]
name = "zms-tradition-bot-template"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="1.44.1", features = ["full"] }
warp = "0.3.7"

